console.log('dom')

let title = document.createElement("h1")
let texto = document.createTextNode('Soy un titulo')
title.appendChild(texto)
document.getElementById('caja').appendChild(title)

let ul = document.createElement("ul")
let li = document.createElement("li")
let ahref = document.createElement("a")
let item1 = document.createTextNode('Item 1')
ul.appendChild(li)
li.appendChild(ahref)
ahref.appendChild(item1)
document.getElementById('caja').appendChild(ul)

let ul2 = document.createElement("ul")
let li2 = document.createElement("li")
let ahref2 = document.createElement("a")
let item2 = document.createTextNode('Item 2')
ul2.appendChild(li2)
li2.appendChild(ahref2)
ahref2.appendChild(item2)
document.getElementById('caja2').appendChild(ul2)